/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TitleAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'ImagesAPI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetImage': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}